name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 11 Pro Max,OS=14.4']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Up & Testing
        run: |
          cd Example
          pod install
          xcrun simctl list
          xcodebuild clean test -workspace StockInfo.xcworkspace -scheme StockInfo -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=14.4'
      - name: Code coverage
        run: bash <(curl -s https://codecov.io/bash)
      - name: Package Test
        run: |
          swift test
