name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 13,OS=16.0']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Up & Testing
        run: swift test
      - name: Code coverage
        run: bash <(curl -s https://codecov.io/bash)
